# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fruteria.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(771, 374)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(400, 310, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.formLayoutWidget = QtGui.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 60, 161, 111))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.op_ma = QtGui.QCheckBox(self.formLayoutWidget)
        self.op_ma.setObjectName(_fromUtf8("op_ma"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.op_ma)
        self.cant_ma = QtGui.QSpinBox(self.formLayoutWidget)
        self.cant_ma.setWrapping(False)
        self.cant_ma.setKeyboardTracking(True)
        self.cant_ma.setObjectName(_fromUtf8("cant_ma"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cant_ma)
        self.op_pe = QtGui.QCheckBox(self.formLayoutWidget)
        self.op_pe.setObjectName(_fromUtf8("op_pe"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.op_pe)
        self.cant_pe = QtGui.QSpinBox(self.formLayoutWidget)
        self.cant_pe.setObjectName(_fromUtf8("cant_pe"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cant_pe)
        self.op_pl = QtGui.QCheckBox(self.formLayoutWidget)
        self.op_pl.setObjectName(_fromUtf8("op_pl"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.op_pl)
        self.cant_pl = QtGui.QSpinBox(self.formLayoutWidget)
        self.cant_pl.setObjectName(_fromUtf8("cant_pl"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cant_pl)
        self.precio_fruta = QtGui.QLineEdit(self.formLayoutWidget)
        self.precio_fruta.setReadOnly(True)
        self.precio_fruta.setObjectName(_fromUtf8("precio_fruta"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.precio_fruta)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.formLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(240, 60, 151, 111))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.op_ac = QtGui.QCheckBox(self.formLayoutWidget_2)
        self.op_ac.setObjectName(_fromUtf8("op_ac"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.op_ac)
        self.cant_ac = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.cant_ac.setObjectName(_fromUtf8("cant_ac"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.cant_ac)
        self.op_bo = QtGui.QCheckBox(self.formLayoutWidget_2)
        self.op_bo.setObjectName(_fromUtf8("op_bo"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.op_bo)
        self.cant_bo = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.cant_bo.setObjectName(_fromUtf8("cant_bo"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.cant_bo)
        self.op_ca = QtGui.QCheckBox(self.formLayoutWidget_2)
        self.op_ca.setObjectName(_fromUtf8("op_ca"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.op_ca)
        self.cant_ca = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.cant_ca.setObjectName(_fromUtf8("cant_ca"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.cant_ca)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.precio_verdura = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.precio_verdura.setReadOnly(True)
        self.precio_verdura.setObjectName(_fromUtf8("precio_verdura"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.precio_verdura)
        self.formLayoutWidget_3 = QtGui.QWidget(Dialog)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(420, 60, 161, 111))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.op_al = QtGui.QCheckBox(self.formLayoutWidget_3)
        self.op_al.setObjectName(_fromUtf8("op_al"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.op_al)
        self.cant_al = QtGui.QSpinBox(self.formLayoutWidget_3)
        self.cant_al.setObjectName(_fromUtf8("cant_al"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.cant_al)
        self.op_le = QtGui.QCheckBox(self.formLayoutWidget_3)
        self.op_le.setObjectName(_fromUtf8("op_le"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.op_le)
        self.cant_le = QtGui.QSpinBox(self.formLayoutWidget_3)
        self.cant_le.setObjectName(_fromUtf8("cant_le"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.cant_le)
        self.op_ga = QtGui.QCheckBox(self.formLayoutWidget_3)
        self.op_ga.setObjectName(_fromUtf8("op_ga"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.op_ga)
        self.cant_ga = QtGui.QSpinBox(self.formLayoutWidget_3)
        self.cant_ga.setObjectName(_fromUtf8("cant_ga"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.cant_ga)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_6)
        self.precio_legumbre = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.precio_legumbre.setReadOnly(True)
        self.precio_legumbre.setObjectName(_fromUtf8("precio_legumbre"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.precio_legumbre)
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(240, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(420, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.salida = QtGui.QLabel(Dialog)
        self.salida.setGeometry(QtCore.QRect(50, 270, 701, 31))
        self.salida.setText(_fromUtf8(""))
        self.salida.setAlignment(QtCore.Qt.AlignCenter)
        self.salida.setObjectName(_fromUtf8("salida"))
        self.formLayoutWidget_4 = QtGui.QWidget(Dialog)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(60, 210, 141, 41))
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_5 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_8 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.total_fruta = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.total_fruta.setObjectName(_fromUtf8("total_fruta"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.total_fruta)
        self.formLayoutWidget_5 = QtGui.QWidget(Dialog)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(240, 210, 151, 41))
        self.formLayoutWidget_5.setObjectName(_fromUtf8("formLayoutWidget_5"))
        self.formLayout_6 = QtGui.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.total_verdura = QtGui.QLineEdit(self.formLayoutWidget_5)
        self.total_verdura.setObjectName(_fromUtf8("total_verdura"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.total_verdura)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.formLayoutWidget_6 = QtGui.QWidget(Dialog)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(420, 210, 161, 41))
        self.formLayoutWidget_6.setObjectName(_fromUtf8("formLayoutWidget_6"))
        self.formLayout_7 = QtGui.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.label_10 = QtGui.QLabel(self.formLayoutWidget_6)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.total_legumbre = QtGui.QLineEdit(self.formLayoutWidget_6)
        self.total_legumbre.setObjectName(_fromUtf8("total_legumbre"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.total_legumbre)
        self.boton_pedido = QtGui.QPushButton(Dialog)
        self.boton_pedido.setGeometry(QtCore.QRect(610, 60, 141, 181))
        self.boton_pedido.setObjectName(_fromUtf8("boton_pedido"))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.op_ma.setText(_translate("Dialog", "Manzanas", None))
        self.op_pe.setText(_translate("Dialog", "Peras", None))
        self.op_pl.setText(_translate("Dialog", "Plátanos", None))
        self.label_4.setText(_translate("Dialog", "Precio/unidad:", None))
        self.op_ac.setText(_translate("Dialog", "Acelga", None))
        self.op_bo.setText(_translate("Dialog", "Borraja", None))
        self.op_ca.setText(_translate("Dialog", "Cardo", None))
        self.label_5.setText(_translate("Dialog", "Precio/Kg:", None))
        self.op_al.setText(_translate("Dialog", "Alubias", None))
        self.op_le.setText(_translate("Dialog", "Lentejas", None))
        self.op_ga.setText(_translate("Dialog", "Garbanzos", None))
        self.label_6.setText(_translate("Dialog", "Precio/500g:", None))
        self.label.setText(_translate("Dialog", "Fruta", None))
        self.label_2.setText(_translate("Dialog", "Verdura", None))
        self.label_3.setText(_translate("Dialog", "Legumbre", None))
        self.label_8.setText(_translate("Dialog", "Total fruta:", None))
        self.label_9.setText(_translate("Dialog", "Total verdura:", None))
        self.label_10.setText(_translate("Dialog", "Total legumbre:", None))
        self.boton_pedido.setText(_translate("Dialog", "Hacer pedido", None))

