# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gas.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(682, 480)
        self.gridLayoutWidget = QtGui.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(100, 100, 111, 100))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.marzo = QtGui.QLineEdit(self.gridLayoutWidget)
        self.marzo.setFrame(False)
        self.marzo.setObjectName(_fromUtf8("marzo"))
        self.gridLayout.addWidget(self.marzo, 2, 1, 1, 1)
        self.enero = QtGui.QLineEdit(self.gridLayoutWidget)
        self.enero.setFrame(False)
        self.enero.setObjectName(_fromUtf8("enero"))
        self.gridLayout.addWidget(self.enero, 0, 1, 1, 1)
        self.febrero = QtGui.QLineEdit(self.gridLayoutWidget)
        self.febrero.setFrame(False)
        self.febrero.setObjectName(_fromUtf8("febrero"))
        self.gridLayout.addWidget(self.febrero, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.abril = QtGui.QLineEdit(self.gridLayoutWidget)
        self.abril.setFrame(False)
        self.abril.setObjectName(_fromUtf8("abril"))
        self.gridLayout.addWidget(self.abril, 3, 1, 1, 1)
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 60, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.line = QtGui.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(340, 20, 16, 221))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.barra_e = QtGui.QProgressBar(Dialog)
        self.barra_e.setGeometry(QtCore.QRect(380, 58, 31, 170))
        self.barra_e.setMaximum(200)
        self.barra_e.setProperty("value", 0)
        self.barra_e.setTextVisible(True)
        self.barra_e.setOrientation(QtCore.Qt.Vertical)
        self.barra_e.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.barra_e.setObjectName(_fromUtf8("barra_e"))
        self.line_3 = QtGui.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(320, 220, 331, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.barra_f = QtGui.QProgressBar(Dialog)
        self.barra_f.setGeometry(QtCore.QRect(440, 58, 31, 170))
        self.barra_f.setMaximum(200)
        self.barra_f.setProperty("value", 0)
        self.barra_f.setOrientation(QtCore.Qt.Vertical)
        self.barra_f.setObjectName(_fromUtf8("barra_f"))
        self.barra_m = QtGui.QProgressBar(Dialog)
        self.barra_m.setGeometry(QtCore.QRect(500, 58, 31, 170))
        self.barra_m.setMaximum(200)
        self.barra_m.setProperty("value", 0)
        self.barra_m.setOrientation(QtCore.Qt.Vertical)
        self.barra_m.setObjectName(_fromUtf8("barra_m"))
        self.barra_a = QtGui.QProgressBar(Dialog)
        self.barra_a.setGeometry(QtCore.QRect(560, 58, 31, 170))
        self.barra_a.setMaximum(200)
        self.barra_a.setProperty("value", 0)
        self.barra_a.setOrientation(QtCore.Qt.Vertical)
        self.barra_a.setObjectName(_fromUtf8("barra_a"))
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(340, 51, 21, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_4 = QtGui.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(340, 135, 21, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(309, 133, 31, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(311, 48, 51, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.dial = QtGui.QDial(Dialog)
        self.dial.setGeometry(QtCore.QRect(110, 310, 161, 111))
        self.dial.setMaximum(100)
        self.dial.setSliderPosition(0)
        self.dial.setInvertedAppearance(False)
        self.dial.setWrapping(False)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName(_fromUtf8("dial"))
        self.volumen = QtGui.QProgressBar(Dialog)
        self.volumen.setGeometry(QtCore.QRect(300, 340, 261, 61))
        self.volumen.setProperty("value", 0)
        self.volumen.setTextVisible(True)
        self.volumen.setObjectName(_fromUtf8("volumen"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(150, 417, 46, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(220, 417, 21, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(300, 300, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.e1 = QtGui.QLabel(Dialog)
        self.e1.setGeometry(QtCore.QRect(380, 240, 46, 13))
        self.e1.setObjectName(_fromUtf8("e1"))
        self.e2 = QtGui.QLabel(Dialog)
        self.e2.setGeometry(QtCore.QRect(437, 240, 46, 13))
        self.e2.setObjectName(_fromUtf8("e2"))
        self.e3 = QtGui.QLabel(Dialog)
        self.e3.setGeometry(QtCore.QRect(504, 240, 46, 13))
        self.e3.setObjectName(_fromUtf8("e3"))
        self.e4 = QtGui.QLabel(Dialog)
        self.e4.setGeometry(QtCore.QRect(565, 240, 46, 13))
        self.e4.setObjectName(_fromUtf8("e4"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.enero, self.febrero)
        Dialog.setTabOrder(self.febrero, self.marzo)
        Dialog.setTabOrder(self.marzo, self.abril)
        Dialog.setTabOrder(self.abril, self.dial)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_3.setText(_translate("Dialog", "Enero", None))
        self.label_2.setText(_translate("Dialog", "Febrero", None))
        self.label_4.setText(_translate("Dialog", "Marzo", None))
        self.label_5.setText(_translate("Dialog", "Abril", None))
        self.label.setText(_translate("Dialog", "Factura Gas", None))
        self.barra_e.setFormat(_translate("Dialog", "p", None))
        self.barra_f.setFormat(_translate("Dialog", "p", None))
        self.barra_m.setFormat(_translate("Dialog", "p", None))
        self.barra_a.setFormat(_translate("Dialog", "p", None))
        self.label_6.setText(_translate("Dialog", "100€", None))
        self.label_7.setText(_translate("Dialog", "200€", None))
        self.label_8.setText(_translate("Dialog", "Max", None))
        self.label_9.setText(_translate("Dialog", "Min", None))
        self.label_10.setText(_translate("Dialog", "Volumen", None))
        self.e1.setText(_translate("Dialog", "Enero", None))
        self.e2.setText(_translate("Dialog", "Febrero", None))
        self.e3.setText(_translate("Dialog", "Marzo", None))
        self.e4.setText(_translate("Dialog", "Abril", None))

